# Generated by Django 5.0.14 on 2025-10-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=60)),
                ("lastname", models.CharField(max_length=60)),
            ],
            options={
                "db_table": "artists",
            },
        ),
    ]
